#!/bin/sh
# -*- mode: shell; -*-

### BEGIN INIT INFO
# Provides:          marcd
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: MA control daemon
# Description:       Measurement Area Control Daemon and Relay.
### END INIT INFO

set -e

NAME="MA Control Daemon"
BINARY=/usr/local/bin/MArCd
CONFIGFILE=/etc/marcd/marcd.conf
PIDFILE=/var/lib/marcd/marcd.pid
MARCD_CONFIG=/etc/default/marcd


. /lib/lsb/init-functions

# Load script configuration
if [ -f ${MARCD_CONFIG} ]; then
	. ${MARCD_CONFIG}
fi

case "$1" in
	start)
		log_daemon_msg "Starting $NAME" "marcd"

		if [ ! -e $CONFIGFILE ]; then
			log_action_msg "No configuration present, create \`$CONFIGFILE' and try again!"
			log_end_msg 1
			exit 1
		fi

		start-stop-daemon --start --chdir ${WORKDIR} --pidfile $PIDFILE --exec $BINARY -- \
			--pidfile $PIDFILE \
			--relay --syslog --daemon --iface ${MARCD_IFACE:-any} \
			-f $CONFIGFILE ${MARCD_OPTS}
		log_end_msg $?
		;;

	stop)
		if [ ! -e $PIDFILE ]; then
			log_action_msg "$NAME does not appear to be running"
			exit
		fi

		log_daemon_msg "Stopping $NAME" "marcd"
		pid=$(cat $PIDFILE)
		start-stop-daemon --stop --signal INT --pidfile $PIDFILE
		if [ -n $pid ]; then
			while kill -0 $pid 2>/dev/null; do
				log_progress_msg "waiting for pid $pid to die"
				sleep 1
			done
		fi
		log_end_msg $?
		;;

	status)
		status_of_proc -p $PIDFILE $BINARY "$NAME"
		;;

	restart)
		$0 stop
		$0 start
		;;

	*)
		echo "Usage: $0 {start|stop|status|restart}"
		exit 2
esac
